name: music_x
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.9
  oktoast: ^2.3.1
  fluro: 1.7.6
  provider: ^4.1.0
  cupertino_back_gesture: ^0.0.2
  flustars: 0.2.6+1
  #flutter_native_splash: ^0.1.9
  encrypt: ^4.0.1
  bot_toast: ^3.0.0
  audioplayers: ^0.15.1
  path_provider: ^1.6.9
  intl: ^0.16.1
  vector_math: ^2.0.8
  permission_handler: ^5.0.0
  cached_network_image: ^2.2.0
  flutter_downloader: ^1.5.2 #歌曲下载
  scrollable_positioned_list: ^0.1.6 #播放列表滚动
  lpinyin: ^1.0.9 #汉字转拼音
  pull_to_refresh: ^1.5.8 #下拉刷新
  #drag_list: ^1.0.8
  reorderables: ^0.3.2 #网格拖动
  flutter_reorderable_list: ^0.1.5 #列表拖动
  flutter_swiper: ^1.1.6
  flutter_staggered_animations: ^0.1.2 #列表动画
  flutter_staggered_grid_view: ^0.3.0 #国外瀑布流
  waterfall_flow: ^2.0.2 #国内瀑布流
  rxdart: ^0.24.1 #store卡顿换这个
  #im_flutter_sdk: ^1.0.0
  im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: dev
  #extended_text_field: ^4.0.0
  extended_text_field: ^5.0.0
  extended_image: ^1.1.0
  image_picker: ^0.6.7+4
  flutter_sound_lite: ^5.1.1
  #multi_image_picker: ^4.7.12
  #photo: ^0.4.8
  wechat_assets_picker: ^4.2.1
  animations: ^1.1.2 #官方动画
  amap_map_fluttify: ^0.29.0 # 高德
  sliding_up_panel: ^1.0.2 # 抽屉
  fdottedline: ^1.0.1 # 虚线
  flutter_speed_dial: ^1.2.5 # 展开按钮

#flutter_native_splash:
#  image: images/cat.jpeg
#  color: "#ffffff"
#  fill: false

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/face/douyin/
  fonts:
    - family: playMode
      fonts:
        - asset: assets/font/playMode.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#flutter_intl:
#  enabled: false
